name: mobile_health_app
description: Flutter client for Mobile Health MVP – BLE data acquisition
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.3       # BLE stack
  firebase_core: ^3.8.0            # Firestore init
  cloud_firestore: ^5.5.0          # Participant↔device mapping
  googleapis: ^13.1.0              # Pub/Sub REST client
  permission_handler: ^11.3.0      # Runtime BLE + location permissions

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
