name: remote_patient_monitoring
description: Flutter client for Mobile Health MVP – BLE data acquisition
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.3       # BLE stack
  firebase_core: ^3.13.0           # Firestore init
  firebase_auth: ^5.5.3           # Firebase Authentication
  cloud_firestore: ^5.6.7         # Participant↔device mapping
  googleapis: ^14.0.0              # Pub/Sub REST client
  permission_handler: ^12.0.0+1      # Runtime BLE + location permissions
  shared_preferences: ^2.2.3       # Local key-value storage (or latest version)
  uuid: ^4.5.1                     # For unique ID generation
  connectivity_plus: ^6.1.4        # Network connectivity monitoring
  sqflite: ^2.3.0                  # SQLite database
  intl: ^0.20.2                    # Date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
